---
- name: installing and launching filebeat
  hosts: webservers
  remote_user: sysadmin
  become: true
  tasks:
 
  - name: download filebeat deb
    shell: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: install filebeat deb
    shell: dpkg -i filebeat-7.4.0-amd64.deb

  - name: drop in filebeat.yml 
    copy:  
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable and configure system module
    shell: filebeat modules enable system

  - name: setup filebeat
    shell: sudo filebeat setup

  - name: start filebeat service
    shell: sudo service filebeat start

  - name: enable service filebeat on boot
    systemd:
      name: filebeat
      enabled: yes

  - name: download metricbeat deb
    shell: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: dpkg
    shell: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
